package A;

import java.util.Arrays;
import java.util.HashMap;

public final class j
{
    public int a;
    public final m b;
    public final l c;
    public final k d;
    public final n e;
    public HashMap f;
    
    public j() {
        final Object b = new Object();
        ((m)b).a = 0;
        ((m)b).b = 0;
        ((m)b).c = 1.0f;
        ((m)b).d = Float.NaN;
        this.b = (m)b;
        final Object c = new Object();
        ((l)c).a = -1;
        ((l)c).b = 0;
        ((l)c).c = -1;
        ((l)c).d = Float.NaN;
        ((l)c).e = Float.NaN;
        ((l)c).f = Float.NaN;
        ((l)c).g = -1;
        ((l)c).h = null;
        ((l)c).i = -1;
        this.c = (l)c;
        final Object d = new Object();
        ((k)d).a = false;
        ((k)d).d = -1;
        ((k)d).e = -1;
        ((k)d).f = -1.0f;
        ((k)d).g = true;
        ((k)d).h = -1;
        ((k)d).i = -1;
        ((k)d).j = -1;
        ((k)d).k = -1;
        ((k)d).l = -1;
        ((k)d).m = -1;
        ((k)d).n = -1;
        ((k)d).o = -1;
        ((k)d).p = -1;
        ((k)d).q = -1;
        ((k)d).r = -1;
        ((k)d).s = -1;
        ((k)d).t = -1;
        ((k)d).u = -1;
        ((k)d).v = -1;
        ((k)d).w = 0.5f;
        ((k)d).x = 0.5f;
        ((k)d).y = null;
        ((k)d).z = -1;
        ((k)d).A = 0;
        ((k)d).B = 0.0f;
        ((k)d).C = -1;
        ((k)d).D = -1;
        ((k)d).E = -1;
        ((k)d).F = 0;
        ((k)d).G = 0;
        ((k)d).H = 0;
        ((k)d).I = 0;
        ((k)d).J = 0;
        ((k)d).K = 0;
        ((k)d).L = 0;
        ((k)d).M = Integer.MIN_VALUE;
        ((k)d).N = Integer.MIN_VALUE;
        ((k)d).O = Integer.MIN_VALUE;
        ((k)d).P = Integer.MIN_VALUE;
        ((k)d).Q = Integer.MIN_VALUE;
        ((k)d).R = Integer.MIN_VALUE;
        ((k)d).S = Integer.MIN_VALUE;
        ((k)d).T = -1.0f;
        ((k)d).U = -1.0f;
        ((k)d).V = 0;
        ((k)d).W = 0;
        ((k)d).X = 0;
        ((k)d).Y = 0;
        ((k)d).Z = 0;
        ((k)d).a0 = 0;
        ((k)d).b0 = 0;
        ((k)d).c0 = 0;
        ((k)d).d0 = 1.0f;
        ((k)d).e0 = 1.0f;
        ((k)d).f0 = -1;
        ((k)d).g0 = 0;
        ((k)d).h0 = -1;
        ((k)d).l0 = false;
        ((k)d).m0 = false;
        ((k)d).n0 = true;
        ((k)d).o0 = 0;
        this.d = (k)d;
        final Object e = new Object();
        ((n)e).a = 0.0f;
        ((n)e).b = 0.0f;
        ((n)e).c = 0.0f;
        ((n)e).d = 1.0f;
        ((n)e).e = 1.0f;
        ((n)e).f = Float.NaN;
        ((n)e).g = Float.NaN;
        ((n)e).h = -1;
        ((n)e).i = 0.0f;
        ((n)e).j = 0.0f;
        ((n)e).k = 0.0f;
        ((n)e).l = false;
        ((n)e).m = 0.0f;
        this.e = (n)e;
        this.f = new HashMap();
    }
    
    public final void a(final e e) {
        final k d = this.d;
        e.e = d.h;
        e.f = d.i;
        e.g = d.j;
        e.h = d.k;
        e.i = d.l;
        e.j = d.m;
        e.k = d.n;
        e.l = d.o;
        e.m = d.p;
        e.n = d.q;
        e.o = d.r;
        e.s = d.s;
        e.t = d.t;
        e.u = d.u;
        e.v = d.v;
        e.leftMargin = d.F;
        e.rightMargin = d.G;
        e.topMargin = d.H;
        e.bottomMargin = d.I;
        e.A = d.R;
        e.B = d.Q;
        e.x = d.N;
        e.z = d.P;
        e.E = d.w;
        e.F = d.x;
        e.p = d.z;
        e.q = d.A;
        e.r = d.B;
        e.G = d.y;
        e.T = d.C;
        e.U = d.D;
        e.I = d.T;
        e.H = d.U;
        e.K = d.W;
        e.J = d.V;
        e.W = d.l0;
        e.X = d.m0;
        e.L = d.X;
        e.M = d.Y;
        e.P = d.Z;
        e.Q = d.a0;
        e.N = d.b0;
        e.O = d.c0;
        e.R = d.d0;
        e.S = d.e0;
        e.V = d.E;
        e.c = d.f;
        e.a = d.d;
        e.b = d.e;
        e.width = d.b;
        e.height = d.c;
        final String k0 = d.k0;
        if (k0 != null) {
            e.Y = k0;
        }
        e.Z = d.o0;
        e.setMarginStart(d.K);
        e.setMarginEnd(d.J);
        e.a();
    }
    
    public final Object clone() {
        final j j = new j();
        final k d = j.d;
        d.getClass();
        final k d2 = this.d;
        d.a = d2.a;
        d.b = d2.b;
        d.c = d2.c;
        d.d = d2.d;
        d.e = d2.e;
        d.f = d2.f;
        d.g = d2.g;
        d.h = d2.h;
        d.i = d2.i;
        d.j = d2.j;
        d.k = d2.k;
        d.l = d2.l;
        d.m = d2.m;
        d.n = d2.n;
        d.o = d2.o;
        d.p = d2.p;
        d.q = d2.q;
        d.r = d2.r;
        d.s = d2.s;
        d.t = d2.t;
        d.u = d2.u;
        d.v = d2.v;
        d.w = d2.w;
        d.x = d2.x;
        d.y = d2.y;
        d.z = d2.z;
        d.A = d2.A;
        d.B = d2.B;
        d.C = d2.C;
        d.D = d2.D;
        d.E = d2.E;
        d.F = d2.F;
        d.G = d2.G;
        d.H = d2.H;
        d.I = d2.I;
        d.J = d2.J;
        d.K = d2.K;
        d.L = d2.L;
        d.M = d2.M;
        d.N = d2.N;
        d.O = d2.O;
        d.P = d2.P;
        d.Q = d2.Q;
        d.R = d2.R;
        d.S = d2.S;
        d.T = d2.T;
        d.U = d2.U;
        d.V = d2.V;
        d.W = d2.W;
        d.X = d2.X;
        d.Y = d2.Y;
        d.Z = d2.Z;
        d.a0 = d2.a0;
        d.b0 = d2.b0;
        d.c0 = d2.c0;
        d.d0 = d2.d0;
        d.e0 = d2.e0;
        d.f0 = d2.f0;
        d.g0 = d2.g0;
        d.h0 = d2.h0;
        d.k0 = d2.k0;
        final int[] i0 = d2.i0;
        if (i0 != null && d2.j0 == null) {
            d.i0 = Arrays.copyOf(i0, i0.length);
        }
        else {
            d.i0 = null;
        }
        d.j0 = d2.j0;
        d.l0 = d2.l0;
        d.m0 = d2.m0;
        d.n0 = d2.n0;
        d.o0 = d2.o0;
        final l c = j.c;
        c.getClass();
        final l c2 = this.c;
        c2.getClass();
        c.a = c2.a;
        c.c = c2.c;
        c.e = c2.e;
        c.d = c2.d;
        final m b = j.b;
        final m b2 = this.b;
        b.a = b2.a;
        b.c = b2.c;
        b.d = b2.d;
        b.b = b2.b;
        final n e = j.e;
        e.getClass();
        final n e2 = this.e;
        e2.getClass();
        e.a = e2.a;
        e.b = e2.b;
        e.c = e2.c;
        e.d = e2.d;
        e.e = e2.e;
        e.f = e2.f;
        e.g = e2.g;
        e.h = e2.h;
        e.i = e2.i;
        e.j = e2.j;
        e.k = e2.k;
        e.l = e2.l;
        e.m = e2.m;
        j.a = this.a;
        return j;
    }
}
