package K2;

import C3.f;
import R3.b;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import java.util.ArrayList;
import java.util.List;

public abstract class w
{
    public static final F A;
    public static final F A0;
    public static final F B;
    public static final F B0;
    public static final F C;
    public static final F C0;
    public static final F D;
    public static final F D0;
    public static final F E;
    public static final F E0;
    public static final F F;
    public static final F F0;
    public static final F G;
    public static final F G0;
    public static final F H;
    public static final F H0;
    public static final F I;
    public static final F I0;
    public static final F J;
    public static final F J0;
    public static final F K;
    public static final F K0;
    public static final F L;
    public static final F L0;
    public static final F M;
    public static final F M0;
    public static final F N;
    public static final F N0;
    public static final F O;
    public static final F O0;
    public static final F P;
    public static final F P0;
    public static final F Q;
    public static final F Q0;
    public static final F R;
    public static final F R0;
    public static final F S;
    public static final F S0;
    public static final F T;
    public static final F T0;
    public static final F U;
    public static final F U0;
    public static final F V;
    public static final F V0;
    public static final F W;
    public static final F W0;
    public static final F X;
    public static final F X0;
    public static final F Y;
    public static final F Y0;
    public static final F Z;
    public static final F Z0;
    public static final List a;
    public static final F a0;
    public static final F a1;
    public static final F b;
    public static final F b0;
    public static final F b1;
    public static final F c;
    public static final F c0;
    public static final F c1;
    public static final F d;
    public static final F d0;
    public static final F d1;
    public static final F e;
    public static final F e0;
    public static final F e1;
    public static final F f;
    public static final F f0;
    public static final F f1;
    public static final F g;
    public static final F g0;
    public static final F g1;
    public static final F h;
    public static final F h0;
    public static final F h1;
    public static final F i;
    public static final F i0;
    public static final F i1;
    public static final F j;
    public static final F j0;
    public static final F j1;
    public static final F k;
    public static final F k0;
    public static final F k1;
    public static final F l;
    public static final F l0;
    public static final F m;
    public static final F m0;
    public static final F n;
    public static final F n0;
    public static final F o;
    public static final F o0;
    public static final F p;
    public static final F p0;
    public static final F q;
    public static final F q0;
    public static final F r;
    public static final F r0;
    public static final F s;
    public static final F s0;
    public static final F t;
    public static final F t0;
    public static final F u;
    public static final F u0;
    public static final F v;
    public static final F v0;
    public static final F w;
    public static final F w0;
    public static final F x;
    public static final F x0;
    public static final F y;
    public static final F y0;
    public static final F z;
    public static final F z0;
    
    static {
        a = Collections.synchronizedList((List)new ArrayList());
        Collections.synchronizedSet((Set)new HashSet());
        final Long value = 10000L;
        b = a("measurement.ad_id_cache_time", value, (E)new b(9), false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, (E)new z(0), false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, (E)new z(6), false);
        e = a("measurement.config.cache_time", 86400000L, (E)new z(12), false);
        f = a("measurement.config.url_scheme", "https", (E)new z(18), false);
        g = a("measurement.config.url_authority", "app-measurement.com", (E)new z(24), false);
        h = a("measurement.upload.max_bundles", 100, (E)new C(0), false);
        i = a("measurement.upload.max_batch_size", 65536, (E)new C(6), false);
        j = a("measurement.upload.max_bundle_size", 65536, (E)new b(14), false);
        k = a("measurement.upload.max_events_per_bundle", 1000, (E)new b(20), false);
        l = a("measurement.upload.max_events_per_day", 100000, (E)new f(20), false);
        m = a("measurement.upload.max_error_events_per_day", 1000, (E)new f(25), false);
        n = a("measurement.upload.max_public_events_per_day", 50000, (E)new b(26), false);
        o = a("measurement.upload.max_conversions_per_day", 10000, (E)new f(26), false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, (E)new b(27), false);
        q = a("measurement.store.max_stored_events_per_app", 100000, (E)new f(27), false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", (E)new b(28), false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s", (E)new f(28), false);
        t = a("measurement.upload.backoff_period", 43200000L, (E)new b(29), false);
        a("measurement.upload.window_interval", 3600000L, (E)new f(29), false);
        u = a("measurement.upload.interval", 3600000L, (E)new A(1), false);
        v = a("measurement.upload.realtime_upload_interval", value, (E)new z(1), false);
        w = a("measurement.upload.debug_upload_interval", 1000L, (E)new A(2), false);
        x = a("measurement.upload.minimum_delay", 500L, (E)new z(2), false);
        y = a("measurement.alarm_manager.minimum_interval", 60000L, (E)new A(3), false);
        z = a("measurement.upload.stale_data_deletion_interval", 86400000L, (E)new z(3), false);
        A = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, (E)new A(4), false);
        B = a("measurement.upload.initial_upload_delay_time", 15000L, (E)new z(4), false);
        C = a("measurement.upload.retry_time", 1800000L, (E)new A(5), false);
        D = a("measurement.upload.retry_count", 6, (E)new A(6), false);
        E = a("measurement.upload.max_queue_time", 518400000L, (E)new A(7), false);
        F = a("measurement.upload.google_signal_max_queue_time", 300000L, (E)new z(7), false);
        G = a("measurement.lifetimevalue.max_currency_tracked", 4, (E)new A(8), false);
        H = a("measurement.audience.filter_result_max_count", 200, (E)new z(8), false);
        I = a("measurement.upload.max_public_user_properties", 100, null, false);
        J = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        K = a("measurement.upload.max_public_event_params", 100, null, false);
        L = a("measurement.service_client.idle_disconnect_millis", 5000L, (E)new A(9), false);
        final Boolean false = Boolean.FALSE;
        M = a("measurement.test.boolean_flag", false, (E)new z(9), false);
        N = a("measurement.test.string_flag", "---", (E)new A(10), false);
        O = a("measurement.test.long_flag", -1L, (E)new z(10), false);
        a("measurement.test.cached_long_flag", -1L, (E)new z(11), true);
        P = a("measurement.test.int_flag", -2, (E)new A(12), false);
        Q = a("measurement.test.double_flag", -3.0, (E)new A(13), false);
        R = a("measurement.experiment.max_ids", 50, (E)new z(13), false);
        S = a("measurement.upload.max_item_scoped_custom_parameters", 27, (E)new A(14), false);
        T = a("measurement.upload.max_event_parameter_value_length", 500, (E)new z(14), true);
        U = a("measurement.max_bundles_per_iteration", 100, (E)new A(15), false);
        V = a("measurement.sdk.attribution.cache.ttl", 604800000L, (E)new z(15), false);
        W = a("measurement.redaction.app_instance_id.ttl", 7200000L, (E)new A(16), false);
        X = a("measurement.rb.attribution.client.min_ad_services_version", 7, (E)new A(17), false);
        Y = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, (E)new z(17), false);
        Z = a("measurement.rb.attribution.uri_scheme", "https", (E)new A(18), false);
        a0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", (E)new A(19), false);
        b0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", (E)new z(19), false);
        c0 = a("measurement.session.engagement_interval", 3600000L, (E)new A(20), false);
        d0 = a("measurement.rb.attribution.app_allowlist", "com.labpixies.flood,com.sofascore.results,games.spearmint.triplecrush,com.block.juggle,io.supercent.linkedcubic,com.cdtg.gunsound,com.corestudios.storemanagementidle,com.cdgames.fidget3d,io.supercent.burgeridle,io.supercent.pizzaidle,jp.ne.ibis.ibispaintx.app,com.dencreak.dlcalculator,com.ebay.kleinanzeigen,de.wetteronline.wetterapp,com.game.shape.shift,com.champion.cubes,bubbleshooter.orig,com.wolt.android,com.master.hotelmaster,com.games.bus.arrival,com.playstrom.dop2,com.huuuge.casino.slots,com.ig.spider.fighting,com.jura.coloring.page,com.rikkogame.ragdoll2,com.ludo.king,com.sigma.prank.sound.haircut,com.crazy.block.robo.monster.cliffs.craft,com.fugo.wow,com.maps.locator.gps.gpstracker.phone,com.gamovation.tileclub,com.pronetis.ironball2,com.meesho.supply,pdf.pdfreader.viewer.editor.free,com.dino.race.master,com.ig.moto.racing,ai.photo.enhancer.photoclear,com.duolingo,com.candle.magic_piano,com.free.vpn.super.hotspot.open,sg.bigo.live,com.cdg.tictactoe,com.zhiliaoapp.musically.go,com.wildspike.wormszone,com.mast.status.video.edit,com.vyroai.photoeditorone,com.pujiagames.deeeersimulator,com.superbinogo.jungleboyadventure,com.trustedapp.pdfreaderpdfviewer,com.artimind.aiart.artgenerator.artavatar,de.cellular.ottohybrid,com.zeptolab.cats.google,in.crossy.daily_crossword", (E)new z(20), false);
        e0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", (E)new A(21), false);
        f0 = a("measurement.rb.attribution.event_params", "value|currency", (E)new z(21), false);
        g0 = a("measurement.rb.attribution.query_parameters_to_remove", "", (E)new z(22), false);
        h0 = a("measurement.rb.attribution.max_queue_time", 1209600000L, (E)new A(23), false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, (E)new z(23), false);
        i0 = a("measurement.rb.max_trigger_registrations_per_day", 0, (E)new A(24), false);
        final Boolean true = Boolean.TRUE;
        j0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", true, (E)new A(25), false);
        k0 = a("measurement.config.notify_trigger_uris_on_backgrounded", true, (E)new z(25), false);
        a("measurement.collection.log_event_and_bundle_v2", true, (E)new A(26), false);
        l0 = a("measurement.quality.checksum", false, null, false);
        m0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, (E)new z(26), false);
        n0 = a("measurement.audience.refresh_event_count_filters_timestamp", false, (E)new A(27), false);
        o0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, (E)new A(28), true);
        p0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, (E)new z(28), false);
        q0 = a("measurement.integration.disable_firebase_instance_id", false, (E)new A(29), false);
        r0 = a("measurement.collection.service.update_with_analytics_fix", false, (E)new z(29), false);
        s0 = a("measurement.service.storage_consent_support_version", 203600, (E)new D(0), false);
        t0 = a("measurement.service.store_null_safelist", true, (E)new D(1), false);
        u0 = a("measurement.service.store_safelist", true, (E)new C(1), false);
        v0 = a("measurement.session_stitching_token_enabled", false, (E)new D(2), false);
        w0 = a("measurement.sgtm.service", true, (E)new C(2), true);
        x0 = a("measurement.sgtm.preview_mode_enabled", true, (E)new C(3), true);
        y0 = a("measurement.sgtm.rollout_percentage_fix", false, (E)new D(4), true);
        z0 = a("measurement.sgtm.app_allowlist", "de.zalando.mobile.internal,de.zalando.mobile.internal.debug,de.zalando.lounge.dev,grit.storytel.app,com.rbc.mobile.android,com.rbc.mobile.android,com.dylvian.mango.activities,com.home24.android,com.home24.android.staging,se.lf.mobile.android,se.lf.mobile.android.beta,se.lf.mobile.android.rc,se.lf.mobile.android.test,se.lf.mobile.android.test.debug,com.boots.flagship.android,com.boots.flagshiproi.android,de.zalando.mobile,com.trivago,com.getyourguide.android,es.mobail.meliarewards,se.nansen.coop.debug,se.nansen.coop,se.coop.coop.qa,com.booking,com.google.firebaseengage,com.mse.mseapp.dev,com.mse.mseapp,pl.eobuwie.eobuwieapp,br.com.eventim.mobile.app.Android,ch.ticketcorner.mobile.app.Android,de.eventim.mobile.app.Android,dk.billetlugen.mobile.app.Android,nl.eventim.mobile.app.Android,com.asos.app,com.blueshieldca.prod,dk.magnetix.tivoliapp,matas.matas.internal,nl.omoda,com.thetrainline,com.simo.androidtest,de.aboutyou.mobile.app,com.hometogo,de.casamundo.casamundomobile,it.casevacanz,eu.coolblue.shop,com.stihl.app,com.indeed.android.jobsearch,com.homeretailgroup.argos.android,com.dylvian.mango.activities.pre,se.nansen.coop.qa", (E)new C(4), true);
        A0 = a("measurement.sgtm.upload_queue", false, (E)new D(5), false);
        B0 = a("measurement.sgtm.google_signal.enable", false, (E)new C(5), false);
        C0 = a("measurement.gmscore_feature_tracking", true, (E)new D(6), false);
        D0 = a("measurement.gmscore_client_telemetry", false, (E)new D(7), false);
        E0 = a("measurement.gmscore_network_migration", false, (E)new C(7), false);
        F0 = a("measurement.fix_health_monitor_stack_trace", true, (E)new C(8), true);
        G0 = a("measurement.rb.attribution.service", true, (E)new f(10), true);
        H0 = a("measurement.rb.attribution.client2", true, (E)new b(11), true);
        I0 = a("measurement.rb.attribution.uuid_generation", true, (E)new f(11), false);
        J0 = a("measurement.rb.attribution.enable_trigger_redaction", true, (E)new b(12), false);
        final Boolean false2 = Boolean.FALSE;
        a("measurement.rb.attribution.followup1.service", false2, (E)new f(12), false);
        K0 = a("measurement.rb.attribution.retry_disposition", false2, (E)new b(13), false);
        L0 = a("measurement.rb.attribution.ad_campaign_info", false2, (E)new f(13), false);
        M0 = a("measurement.rb.attribution.improved_retry", true, (E)new f(14), true);
        N0 = a("measurement.client.sessions.enable_fix_background_engagement", false2, (E)new b(15), false);
        O0 = a("measurement.client.sessions.enable_pause_engagement_in_background", true, (E)new b(16), false);
        P0 = a("measurement.dma_consent.service_dcu_event2", true, (E)new f(16), false);
        Q0 = a("measurement.dma_consent.services_database_update_fix", true, (E)new b(17), false);
        R0 = a("measurement.dma_consent.setting_npa_inline_fix", true, (E)new f(17), false);
        S0 = a("measurement.gbraid_campaign.gbraid.client", true, (E)new b(18), true);
        T0 = a("measurement.gbraid_campaign.gbraid.service", true, (E)new f(18), true);
        U0 = a("measurement.service.consent.pfo_on_fx", true, (E)new b(19), false);
        V0 = a("measurement.service.consent.params_on_fx", true, (E)new f(19), false);
        W0 = a("measurement.consent.stop_reset_on_storage_denied.client", true, (E)new f(24), true);
        X0 = a("measurement.consent.stop_reset_on_storage_denied.service", true, (E)new A(0), true);
        Y0 = a("measurement.consent.scrub_audience_data_analytics_consent", true, (E)new z(5), false);
        Z0 = a("measurement.consent.fix_first_open_count_from_snapshot", true, (E)new A(11), false);
        a1 = a("measurement.fix_engagement_on_reset_analytics_data", true, (E)new z(16), false);
        b1 = a("measurement.rb.attribution.service.bundle_on_backgrounded", true, (E)new A(22), false);
        c1 = a("measurement.rb.attribution.client.bundle_on_backgrounded", true, (E)new z(27), false);
        d1 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", false2, (E)new D(3), false);
        e1 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", false2, (E)new b(10), false);
        f1 = a("measurement.set_default_event_parameters_with_backfill.service", false2, (E)new f(15), false);
        a("measurement.set_default_event_parameters_with_backfill.client.dev", false2, (E)new b(21), false);
        final Boolean true2 = Boolean.TRUE;
        g1 = a("measurement.defensively_copy_bundles_validate_default_params", true2, (E)new f(21), false);
        h1 = a("measurement.fix_origin_in_upload_utils.service", true2, (E)new b(22), false);
        a("measurement.chimera.parameter.service", true2, (E)new f(22), false);
        i1 = a("measurement.service.ad_impression.convert_value_to_double", true2, (E)new b(23), false);
        j1 = a("measurement.persisted_config_defensive_copies", false2, (E)new f(23), false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", true2, (E)new b(24), false);
        k1 = a("measurement.currency.escape_underscore_fix", true2, (E)new b(25), false);
    }
    
    public static F a(final String s, final Object o, final E e, final boolean b) {
        final F f = new F(s, o, e);
        if (b) {
            K2.w.a.add((Object)f);
        }
        return f;
    }
}
